# Generated by Django 6.0.1 on 2026-01-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cause', models.TextField()),
                ('is_contagious', models.BooleanField(default=False)),
                ('suggestted_treatment', models.TextField()),
            ],
        ),
    ]
